### ISSUE TITLE
Servertest fails: SearchTest.handleReservedCharacters() / highlighting()

### ISSUE THREAD

**Issue by cng-pvl** [matterial-com/matterial#46]
These search-tests currently doesn't work:

**handleReservedCharacters**
`
searchResult = this.searchServer.search(Document.INDEX_TYPE_NAME, null, new SearchRequest("pdf a"), null);
`

**highlighting**
`
searchResult = this.searchServer.search(Document.INDEX_TYPE_NAME, null, searchRequest, null);
...
searchResult = this.searchServer.search(Document.INDEX_TYPE_NAME, null, searchRequest, null);
`

It is currently commented...

> [0m[32m13:24:18,910 DEBUG [com.matterial.mtr.search.SearchServer] (default task-1) 
> {
>   "from" : 0,
>   "size" : 10,
>   "query" : {
>     "bool" : {
>       "must" : [
>         {
>           "query_string" : {
>             "query" : "pdf a",
>             "fields" : [
>               "*.ngram^1.0",
>               "_all^1.0"
>             ],
>             "use_dis_max" : true,
>             "tie_breaker" : 0.0,
>             "default_operator" : "or",
>             "auto_generate_phrase_queries" : false,
>             "max_determined_states" : 10000,
>             "enable_position_increment" : true,
>             "fuzziness" : "AUTO",
>             "fuzzy_prefix_length" : 0,
>             "fuzzy_max_expansions" : 50,
>             "phrase_slop" : 0,
>             "minimum_should_match" : "",
>             "escape" : false,
>             "split_on_whitespace" : true,
>             "boost" : 1.0
>           }
>         }
>       ],
>       "disable_coord" : false,
>       "adjust_pure_negative" : true,
>       "boost" : 1.0
>     }
>   },
>   "ext" : { }
> }
> [0m[31m13:24:18,935 ERROR [com.matterial.mtr.search.SearchServer] (default task-1) Error in search!: Failed to execute phase [query_fetch], all shards failed; shardFailures {[ihStwrN6RiKd7qyPO1tcsw][mtr-index-null][0]: RemoteTransportException[[ihStwrN][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: QueryShardException[failed to create query: {
>   "bool" : {
>     "must" : [
>       {
>         "query_string" : {
>           "query" : "pdf a",
>           "fields" : [
>             "*.ngram^1.0",
>             "_all^1.0"
>           ],
>           "use_dis_max" : true,
>           "tie_breaker" : 0.0,
>           "default_operator" : "or",
>           "auto_generate_phrase_queries" : false,
>           "max_determined_states" : 10000,
>           "enable_position_increment" : true,
>           "fuzziness" : "AUTO",
>           "fuzzy_prefix_length" : 0,
>           "fuzzy_max_expansions" : 50,
>           "phrase_slop" : 0,
>           "minimum_should_match" : "",
>           "escape" : false,
>           "split_on_whitespace" : true,
>           "boost" : 1.0
>         }
>       }
>     ],
>     "disable_coord" : false,
>     "adjust_pure_negative" : true,
>     "boost" : 1.0
>   }
> }]; nested: NumberFormatException[For input string: ""]; }
> 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:204)
> 	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:139)
> 	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
> 	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:984)
> 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1091)
> 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1069)
> 	at org.elasticsearch.transport.TransportService$6.onFailure(TransportService.java:588)
> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:512)
> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: RemoteTransportException[[ihStwrN][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: QueryShardException[failed to create query: {
>   "bool" : {
>     "must" : [
>       {
>         "query_string" : {
>           "query" : "pdf a",
>           "fields" : [
>             "*.ngram^1.0",
>             "_all^1.0"
>           ],
>           "use_dis_max" : true,
>           "tie_breaker" : 0.0,
>           "default_operator" : "or",
>           "auto_generate_phrase_queries" : false,
>           "max_determined_states" : 10000,
>           "enable_position_increment" : true,
>           "fuzziness" : "AUTO",
>           "fuzzy_prefix_length" : 0,
>           "fuzzy_max_expansions" : 50,
>           "phrase_slop" : 0,
>           "minimum_should_match" : "",
>           "escape" : false,
>           "split_on_whitespace" : true,
>           "boost" : 1.0
>         }
>       }
>     ],
>     "disable_coord" : false,
>     "adjust_pure_negative" : true,
>     "boost" : 1.0
>   }
> }]; nested: NumberFormatException[For input string: ""];
> Caused by: [mtr-index-null/hI0J3WKcRpi_sCvEPL5eZg] QueryShardException[failed to create query: {
>   "bool" : {
>     "must" : [
>       {
>         "query_string" : {
>           "query" : "pdf a",
>           "fields" : [
>             "*.ngram^1.0",
>             "_all^1.0"
>           ],
>           "use_dis_max" : true,
>           "tie_breaker" : 0.0,
>           "default_operator" : "or",
>           "auto_generate_phrase_queries" : false,
>           "max_determined_states" : 10000,
>           "enable_position_increment" : true,
>           "fuzziness" : "AUTO",
>           "fuzzy_prefix_length" : 0,
>           "fuzzy_max_expansions" : 50,
>           "phrase_slop" : 0,
>           "minimum_should_match" : "",
>           "escape" : false,
>           "split_on_whitespace" : true,
>           "boost" : 1.0
>         }
>       }
>     ],
>     "disable_coord" : false,
>     "adjust_pure_negative" : true,
>     "boost" : 1.0
>   }
> }]; nested: NumberFormatException[For input string: ""];
> 	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:327)
> 	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:305)
> 	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:692)
> 	at org.elasticsearch.search.SearchService.createContext(SearchService.java:553)
> 	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
> 	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:364)
> 	at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:324)
> 	at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:321)
> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
> 	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577)
> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527)
> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NumberFormatException: For input string: ""
> 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> 	at java.lang.Integer.parseInt(Integer.java:592)
> 	at java.lang.Integer.parseInt(Integer.java:615)
> 	at org.elasticsearch.common.lucene.search.Queries.calculateMinShouldMatch(Queries.java:173)
> 	at org.elasticsearch.common.lucene.search.Queries.applyMinimumShouldMatch(Queries.java:126)
> 	at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:1049)
> 	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97)
> 	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:435)
> 	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:409)
> 	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97)
> 	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:306)
> 	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:323)
> 	... 14 more

**Comment by Kartax** [comment]
Fixed
